version: '3.9'

services:

  db:
    image: postgres:16.0-bookworm
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db-notes-misbakh-be-prod
      - POSTGRES_USER=notes-misbakh-be-prod
      - POSTGRES_PASSWORD=tN8Rmp3$8KKBTdcx
    ports:
      - '5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '4001:1323'
    depends_on:
      - db
    pull_policy: build

volumes:
  pgdata:
